import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Adult from "./pageElem/Adult";
import Circle from "./pageElem/circleMenu/circle";
import Child from "./pageElem/Child";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Midicion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
        <div className={styles.header}>
            <p className={styles.fCaption}>А вдруг СМА?</p>
            <p className={styles.sCaption}>Выберите, кто Ваш пациент:</p>
        </div>

      <main className={styles.main}>
          <div className={styles.infoWrap}>
              <Adult/>
              <Child/>
          </div>


          <div className={styles.underText}><span className={styles.underTextBig} >Сообщает ли один из ваших пациентов о следующих симптомах? </span>
              <span className={styles.underTextSmall}>(нажмите на любую иконку и узнайте больше)</span>
          </div>
      </main>

        <Circle/>

    </div>
  )
}
